### GD TRAIN data

# NANO model

# only feature extractor
- model: 'yolov8n.pt'
  saving_directory: runs/detect/GD_freeze_backbone
  data_config:
    dataset_name: 'VOC'
    train_postfix: 'GD'
    val_postfix: 
    test_postfix: 
  train_config:
    data: 'datasets/VOC/VOC.yaml'
    imgsz: 640
    epochs: 100
    workers: 2
    batch: 32
    freeze: 10
    optimizer: 'AdamW'
    lr0: 0.00005
    lrf: 0.01
    patience: 100
  test_config:
    data: 'datasets/VOC/VOC_test.yaml'
    imgsz: 640
    batch: 32

# detection head
- model: 'yolov8n.pt'
  saving_directory: runs/detect/GD_freeze_detection
  data_config:
    dataset_name: 'VOC'
    train_postfix: 'GD'
    val_postfix: 
    test_postfix: 
  train_config:
    data: 'datasets/VOC/VOC.yaml'
    imgsz: 640
    epochs: 100
    workers: 2
    batch: 32
    freeze: 21
    optimizer: 'AdamW'
    lr0: 0.00005
    lrf: 0.01
    patience: 100
  test_config:
    data: 'datasets/VOC/VOC_test.yaml'
    imgsz: 640
    batch: 32

# SMALL model

# only feature extractor
- model: 'yolov8s.pt'
  saving_directory: runs/detect/GD_freeze_backbone
  data_config:
    dataset_name: 'VOC'
    train_postfix: 'GD'
    val_postfix: 
    test_postfix: 
  train_config:
    data: 'datasets/VOC/VOC.yaml'
    imgsz: 640
    epochs: 100
    workers: 2
    batch: 24
    freeze: 10
    optimizer: 'AdamW'
    lr0: 0.00001
    lrf: 0.01
    patience: 100
  test_config:
    data: 'datasets/VOC/VOC_test.yaml'
    imgsz: 640
    batch: 24

# detection head
- model: 'yolov8s.pt'
  saving_directory: runs/detect/GD_freeze_detection
  data_config:
    dataset_name: 'VOC'
    train_postfix: 'GD'
    val_postfix: 
    test_postfix: 
  train_config:
    data: 'datasets/VOC/VOC.yaml'
    imgsz: 640
    epochs: 100
    workers: 2
    batch: 24
    freeze: 21
    optimizer: 'AdamW'
    lr0: 0.00001
    lrf: 0.01
    patience: 100
  test_config:
    data: 'datasets/VOC/VOC_test.yaml'
    imgsz: 640
    batch: 24


### ORIGINAL DATA

# NANO model

# only feature extractor
- model: 'yolov8n.pt'
  saving_directory: runs/detect/orig_freeze_backbone
  data_config:
    dataset_name: 'VOC'
    train_postfix: 
    val_postfix: 
    test_postfix: 
  train_config:
    data: 'datasets/VOC/VOC.yaml'
    imgsz: 640
    epochs: 100
    workers: 2
    batch: 32
    freeze: 10
    optimizer: 'AdamW'
    lr0: 0.00005
    lrf: 0.01
    patience: 100
  test_config:
    data: 'datasets/VOC/VOC_test.yaml'
    imgsz: 640
    batch: 32

# detection head
- model: 'yolov8n.pt'
  saving_directory: runs/detect/orig_freeze_detection
  data_config:
    dataset_name: 'VOC'
    train_postfix: 
    val_postfix: 
    test_postfix: 
  train_config:
    data: 'datasets/VOC/VOC.yaml'
    imgsz: 640
    epochs: 100
    workers: 2
    batch: 32
    freeze: 21
    optimizer: 'AdamW'
    lr0: 0.00005
    lrf: 0.01
    patience: 100
  test_config:
    data: 'datasets/VOC/VOC_test.yaml'
    imgsz: 640
    batch: 32

# SMALL model
# only feature extractor
- model: 'yolov8s.pt'
  saving_directory: runs/detect/orig_freeze_backbone
  data_config:
    dataset_name: 'VOC'
    train_postfix: 
    val_postfix: 
    test_postfix: 
  train_config:
    data: 'datasets/VOC/VOC.yaml'
    imgsz: 640
    epochs: 100
    workers: 2
    batch: 24
    freeze: 10
    optimizer: 'AdamW'
    lr0: 0.00001
    lrf: 0.01
    patience: 100
  test_config:
    data: 'datasets/VOC/VOC_test.yaml'
    imgsz: 640
    batch: 24

# detection head
- model: 'yolov8s.pt'
  saving_directory: runs/detect/orig_freeze_detection
  data_config:
    dataset_name: 'VOC'
    train_postfix: 
    val_postfix: 
    test_postfix: 
  train_config:
    data: 'datasets/VOC/VOC.yaml'
    imgsz: 640
    epochs: 100
    workers: 2
    batch: 24
    freeze: 21
    optimizer: 'AdamW'
    lr0: 0.00001
    lrf: 0.01
    patience: 100
  test_config:
    data: 'datasets/VOC/VOC_test.yaml'
    imgsz: 640
    batch: 24


## GD TRAIN VAL data

# NANO model

# only feature extractor
- model: 'yolov8n.pt'
  saving_directory: runs/detect/GD_train_val_freeze_backbone
  data_config:
    dataset_name: 'VOC'
    train_postfix: 'GD'
    val_postfix: 'GD'
    test_postfix: 
  train_config:
    data: 'datasets/VOC/VOC.yaml'
    imgsz: 640
    epochs: 100
    workers: 2
    batch: 32
    freeze: 10
    optimizer: 'AdamW'
    lr0: 0.00005
    lrf: 0.01
    patience: 100
  test_config:
    data: 'datasets/VOC/VOC_test.yaml'
    imgsz: 640
    batch: 32

# detection head
- model: 'yolov8n.pt'
  saving_directory: runs/detect/GD_train_val_freeze_detection
  data_config:
    dataset_name: 'VOC'
    train_postfix: 'GD'
    val_postfix: 'GD'
    test_postfix: 
  train_config:
    data: 'datasets/VOC/VOC.yaml'
    imgsz: 640
    epochs: 100
    workers: 2
    batch: 32
    freeze: 21
    optimizer: 'AdamW'
    lr0: 0.00005
    lrf: 0.01
    patience: 100
  test_config:
    data: 'datasets/VOC/VOC_test.yaml'
    imgsz: 640
    batch: 32

# SMALL model
# only feature extractor
- model: 'yolov8s.pt'
  saving_directory: runs/detect/GD_train_val_freeze_backbone
  data_config:
    dataset_name: 'VOC'
    train_postfix: 'GD'
    val_postfix: 'GD'
    test_postfix: 
  train_config:
    data: 'datasets/VOC/VOC.yaml'
    imgsz: 640
    epochs: 100
    workers: 2
    batch: 24
    freeze: 10
    optimizer: 'AdamW'
    lr0: 0.00001
    lrf: 0.01
    patience: 100
  test_config:
    data: 'datasets/VOC/VOC_test.yaml'
    imgsz: 640
    batch: 24

# detection head
- model: 'yolov8s.pt'
  saving_directory: runs/detect/GD_train_val_freeze_detection
  data_config:
    dataset_name: 'VOC'
    train_postfix: 'GD'
    val_postfix: 'GD'
    test_postfix: 
  train_config:
    data: 'datasets/VOC/VOC.yaml'
    imgsz: 640
    epochs: 100
    workers: 2
    batch: 24
    freeze: 21
    optimizer: 'AdamW'
    lr0: 0.00001
    lrf: 0.01
    patience: 100
  test_config:
    data: 'datasets/VOC/VOC_test.yaml'
    imgsz: 640
    batch: 24