- model: yolov8n.pt
  saving_directory: runs/all_models/GD_train/nano
  data_config:
    dataset_name: VOC
    train_postfix: GD
    val_postfix: null
    test_postfix: null
  train_config:
    data: datasets/VOC/VOC.yaml
    imgsz: 640
    workers: 2
    optimizer: AdamW
    epochs: 100
    batch: 32
    lr0: 5.0e-05
    lrf: 0.01
    patience: 100
  test_config:
    data: datasets/VOC/VOC_test.yaml
    imgsz: 640
    batch: 32


- model: yolov8s.pt
  saving_directory: runs/all_models/GD_train/small
  data_config:
    dataset_name: VOC
    train_postfix: GD
    val_postfix: null
    test_postfix: null
  train_config:
    data: datasets/VOC/VOC.yaml
    imgsz: 640
    workers: 2
    optimizer: AdamW
    epochs: 100
    batch: 24
    lr0: 1.0e-05
    lrf: 0.01
    patience: 100
  test_config:
    data: datasets/VOC/VOC_test.yaml
    imgsz: 640
    batch: 24


- model: yolov8m.pt
  saving_directory: runs/all_models/GD_train/medium
  data_config:
    dataset_name: VOC
    train_postfix: GD
    val_postfix: null
    test_postfix: null
  train_config:
    data: datasets/VOC/VOC.yaml
    imgsz: 640
    workers: 2
    optimizer: AdamW
    epochs: 150
    batch: 16
    lr0: 5.0e-06
    lrf: 0.01
    patience: 150
  test_config:
    data: datasets/VOC/VOC_test.yaml
    imgsz: 640
    batch: 16


- model: yolov8l.pt
  saving_directory: runs/all_models/GD_train/large
  data_config:
    dataset_name: VOC
    train_postfix: GD
    val_postfix: null
    test_postfix: null
  train_config:
    data: datasets/VOC/VOC.yaml
    imgsz: 640
    workers: 2
    optimizer: AdamW
    epochs: 150
    batch: 12
    lr0: 3.0e-06
    lrf: 0.01
    patience: 150
  test_config:
    data: datasets/VOC/VOC_test.yaml
    imgsz: 640
    batch: 12


- model: yolov8x.pt
  saving_directory: runs/all_models/GD_train/extra_large
  data_config:
    dataset_name: VOC
    train_postfix: GD
    val_postfix: null
    test_postfix: null
  train_config:
    data: datasets/VOC/VOC.yaml
    imgsz: 640
    workers: 2
    optimizer: AdamW
    epochs: 150
    batch: 8
    lr0: 3.0e-06
    lrf: 0.01
    patience: 150
  test_config:
    data: datasets/VOC/VOC_test.yaml
    imgsz: 640
    batch: 8


- model: yolov8n.pt
  saving_directory: runs/all_models/orig/nano
  data_config:
    dataset_name: VOC
    train_postfix: null
    val_postfix: null
    test_postfix: null
  train_config:
    data: datasets/VOC/VOC.yaml
    imgsz: 640
    workers: 2
    optimizer: AdamW
    epochs: 100
    batch: 32
    lr0: 5.0e-05
    lrf: 0.01
    patience: 100
  test_config:
    data: datasets/VOC/VOC_test.yaml
    imgsz: 640
    batch: 32


- model: yolov8s.pt
  saving_directory: runs/all_models/orig/small
  data_config:
    dataset_name: VOC
    train_postfix: null
    val_postfix: null
    test_postfix: null
  train_config:
    data: datasets/VOC/VOC.yaml
    imgsz: 640
    workers: 2
    optimizer: AdamW
    epochs: 100
    batch: 24
    lr0: 1.0e-05
    lrf: 0.01
    patience: 100
  test_config:
    data: datasets/VOC/VOC_test.yaml
    imgsz: 640
    batch: 24


- model: yolov8m.pt
  saving_directory: runs/all_models/orig/medium
  data_config:
    dataset_name: VOC
    train_postfix: null
    val_postfix: null
    test_postfix: null
  train_config:
    data: datasets/VOC/VOC.yaml
    imgsz: 640
    workers: 2
    optimizer: AdamW
    epochs: 150
    batch: 16
    lr0: 5.0e-06
    lrf: 0.01
    patience: 150
  test_config:
    data: datasets/VOC/VOC_test.yaml
    imgsz: 640
    batch: 16


- model: yolov8l.pt
  saving_directory: runs/all_models/orig/large
  data_config:
    dataset_name: VOC
    train_postfix: null
    val_postfix: null
    test_postfix: null
  train_config:
    data: datasets/VOC/VOC.yaml
    imgsz: 640
    workers: 2
    optimizer: AdamW
    epochs: 150
    batch: 12
    lr0: 3.0e-06
    lrf: 0.01
    patience: 150
  test_config:
    data: datasets/VOC/VOC_test.yaml
    imgsz: 640
    batch: 12


- model: yolov8x.pt
  saving_directory: runs/all_models/orig/extra_large
  data_config:
    dataset_name: VOC
    train_postfix: null
    val_postfix: null
    test_postfix: null
  train_config:
    data: datasets/VOC/VOC.yaml
    imgsz: 640
    workers: 2
    optimizer: AdamW
    epochs: 150
    batch: 8
    lr0: 3.0e-06
    lrf: 0.01
    patience: 150
  test_config:
    data: datasets/VOC/VOC_test.yaml
    imgsz: 640
    batch: 8


- model: yolov8n.pt
  saving_directory: runs/all_models/GD_train_val/nano
  data_config:
    dataset_name: VOC
    train_postfix: GD
    val_postfix: GD
    test_postfix: null
  train_config:
    data: datasets/VOC/VOC.yaml
    imgsz: 640
    workers: 2
    optimizer: AdamW
    epochs: 100
    batch: 32
    lr0: 5.0e-05
    lrf: 0.01
    patience: 100
  test_config:
    data: datasets/VOC/VOC_test.yaml
    imgsz: 640
    batch: 32


- model: yolov8s.pt
  saving_directory: runs/all_models/GD_train_val/small
  data_config:
    dataset_name: VOC
    train_postfix: GD
    val_postfix: GD
    test_postfix: null
  train_config:
    data: datasets/VOC/VOC.yaml
    imgsz: 640
    workers: 2
    optimizer: AdamW
    epochs: 100
    batch: 24
    lr0: 1.0e-05
    lrf: 0.01
    patience: 100
  test_config:
    data: datasets/VOC/VOC_test.yaml
    imgsz: 640
    batch: 24


- model: yolov8m.pt
  saving_directory: runs/all_models/GD_train_val/medium
  data_config:
    dataset_name: VOC
    train_postfix: GD
    val_postfix: GD
    test_postfix: null
  train_config:
    data: datasets/VOC/VOC.yaml
    imgsz: 640
    workers: 2
    optimizer: AdamW
    epochs: 150
    batch: 16
    lr0: 5.0e-06
    lrf: 0.01
    patience: 150
  test_config:
    data: datasets/VOC/VOC_test.yaml
    imgsz: 640
    batch: 16


- model: yolov8l.pt
  saving_directory: runs/all_models/GD_train_val/large
  data_config:
    dataset_name: VOC
    train_postfix: GD
    val_postfix: GD
    test_postfix: null
  train_config:
    data: datasets/VOC/VOC.yaml
    imgsz: 640
    workers: 2
    optimizer: AdamW
    epochs: 150
    batch: 12
    lr0: 3.0e-06
    lrf: 0.01
    patience: 150
  test_config:
    data: datasets/VOC/VOC_test.yaml
    imgsz: 640
    batch: 12


- model: yolov8x.pt
  saving_directory: runs/all_models/GD_train_val/extra_large
  data_config:
    dataset_name: VOC
    train_postfix: GD
    val_postfix: GD
    test_postfix: null
  train_config:
    data: datasets/VOC/VOC.yaml
    imgsz: 640
    workers: 2
    optimizer: AdamW
    epochs: 150
    batch: 8
    lr0: 3.0e-06
    lrf: 0.01
    patience: 150
  test_config:
    data: datasets/VOC/VOC_test.yaml
    imgsz: 640
    batch: 8


