- model: 'yolov8n.pt'
  saving_directory: runs/detect/orig_partitial_1_
  data_config:
    dataset_name: 'VOC'
    train_postfix: 
    val_postfix: 
    test_postfix: 
    seed: 1
    number_samples: 500
  train_config:
    data: 'datasets/VOC/VOC.yaml'
    imgsz: 640
    epochs: 3
    workers: 2
    batch: 32
  test_config:
    data: 'datasets/VOC/VOC_test.yaml'
    imgsz: 640
    batch: 16

- model: 'yolov8n.pt'
  saving_directory: runs/detect/orig_partitial_2_
  data_config:
    dataset_name: 'VOC'
    train_postfix: 
    val_postfix: 
    test_postfix: 
    seed: 2
    number_samples: 500
  train_config:
    data: 'datasets/VOC/VOC.yaml'
    imgsz: 640
    epochs: 3
    workers: 2
    batch: 32
  test_config:
    data: 'datasets/VOC/VOC_test.yaml'
    imgsz: 640
    batch: 16

- model: 'yolov8n.pt'
  saving_directory: runs/detect/orig_partitial_3_
  data_config:
    dataset_name: 'VOC'
    train_postfix: 
    val_postfix: 
    test_postfix: 
    seed: 3
    number_samples: 500
  train_config:
    data: 'datasets/VOC/VOC.yaml'
    imgsz: 640
    epochs: 3
    workers: 2
    batch: 32
  test_config:
    data: 'datasets/VOC/VOC_test.yaml'
    imgsz: 640
    batch: 16

# - model: 'yolov8s.pt'
#   saving_directory: runs/detect/orig
#   data_config:
#     dataset_name: 'VOC'
#     train_postfix: 
#     val_postfix: 
#     test_postfix: 
#   train_config:
#     data: 'datasets/VOC/VOC.yaml'
#     imgsz: 640
#     epochs: 150
#     workers: 2
#     batch: 24
#   test_config:
#     data: 'datasets/VOC/VOC_test.yaml'
#     imgsz: 640
#     batch: 16

# - model: 'yolov8m.pt'
#   saving_directory: runs/detect/orig
#   data_config:
#     dataset_name: 'VOC'
#     train_postfix: 
#     val_postfix: 
#     test_postfix: 
#   train_config:
#     data: 'datasets/VOC/VOC.yaml'
#     imgsz: 640
#     epochs: 200
#     workers: 2
#     batch: 16
#   test_config:
#     data: 'datasets/VOC/VOC_test.yaml'
#     imgsz: 640
#     batch: 16

# - model: 'yolov8l.pt'
#   saving_directory: runs/detect/orig
#   data_config:
#     dataset_name: 'VOC'
#     train_postfix: 
#     val_postfix: 
#     test_postfix: 
#   train_config:
#     data: 'datasets/VOC/VOC.yaml'
#     imgsz: 640
#     epochs: 250
#     workers: 2
#     batch: 12
#   test_config:
#     data: 'datasets/VOC/VOC_test.yaml'
#     imgsz: 640
#     batch: 8

# - model: 'yolov8x.pt'
#   saving_directory: runs/detect/orig
#   data_config:
#     dataset_name: 'VOC'
#     train_postfix: 
#     val_postfix: 
#     test_postfix: 
#   train_config:
#     data: 'datasets/VOC/VOC.yaml'
#     imgsz: 640
#     epochs: 200
#     workers: 2
#     batch: 8
#   test_config:
#     data: 'datasets/VOC/VOC_test.yaml'
#     imgsz: 640
#     batch: 8

