- model: 'yolov8n.pt'
  saving_directory: runs/detect/orig
  data_config:
    dataset_name: 'VOC'
    train_postfix: 
    val_postfix: 
    test_postfix: 
  train_config:
    data: 'datasets/VOC/VOC.yaml'
    imgsz: 640
    epochs: 100
    workers: 2
    batch: -1
  test_config:
    data: 'datasets/VOC/VOC_test.yaml'
    imgsz: 640
    batch: 16

- model: 'yolov8s.pt'
  saving_directory: runs/detect/orig
  data_config:
    dataset_name: 'VOC'
    train_postfix: 
    val_postfix: 
    test_postfix: 
  train_config:
    data: 'datasets/VOC/VOC.yaml'
    imgsz: 640
    epochs: 100
    workers: 2
    batch: -1
  test_config:
    data: 'datasets/VOC/VOC_test.yaml'
    imgsz: 640
    batch: 16

- model: 'yolov8m.pt'
  saving_directory: runs/detect/orig
  data_config:
    dataset_name: 'VOC'
    train_postfix: 
    val_postfix: 
    test_postfix: 
  train_config:
    data: 'datasets/VOC/VOC.yaml'
    imgsz: 640
    epochs: 100
    workers: 2
    batch: -1
  test_config:
    data: 'datasets/VOC/VOC_test.yaml'
    imgsz: 640
    batch: 16

- model: 'yolov8l.pt'
  saving_directory: runs/detect/orig
  data_config:
    dataset_name: 'VOC'
    train_postfix: 
    val_postfix: 
    test_postfix: 
  train_config:
    data: 'datasets/VOC/VOC.yaml'
    imgsz: 640
    epochs: 100
    workers: 2
    batch: -1
  test_config:
    data: 'datasets/VOC/VOC_test.yaml'
    imgsz: 640
    batch: 4

- model: 'yolov8x.pt'
  saving_directory: runs/detect/orig
  data_config:
    dataset_name: 'VOC'
    train_postfix: 
    val_postfix: 
    test_postfix: 
  train_config:
    data: 'datasets/VOC/VOC.yaml'
    imgsz: 640
    epochs: 100
    workers: 2
    batch: -1
  test_config:
    data: 'datasets/VOC/VOC_test.yaml'
    imgsz: 640
    batch: 4

# data='../datasets/VOC/VOC.yaml', epochs=1, imgsz=640, workers=2




# - model: MobileNet
#   dataset: ImageNet
#   train: train_
#   test: test_
#   val: validation_
#   saving_directory: /path/to/save/experiment2

# - model: VGG
#   dataset: MNIST
#   train: train_
#   test: test_
#   val: validation_
#   saving_directory: /path/to/save/experiment3


